CREATE DATABASE IF NOT EXISTS barbershop;
USE barbershop;

CREATE TABLE IF NOT EXISTS usuarios(
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(20) NOT NULL
);
